name: video_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  injectable_generator: ^2.6.2
  get_it: ^8.0.2
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter
  video_player: ^2.9.2
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

assets:
     - assets/
     - lib/l10n/intl_en.arb
